version: "3.3"
services:
  postgres:
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "dr"
      POSTGRES_USER: "dr"
      POSTGRES_PASSWORD: "azxswq1e"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  api_server:
    build: ./api_server
    volumes:
      - ./api_server:/code
    environment:
      TZ: Europe/Moscow
    ports:
      - "8765:8765"

  telegram_bot:
    build: ./telegram_bot
    volumes:
      - ./telegram_bot:/code
    environment:
      TZ: Europe/Moscow
    ports:
      - "8443:8443"
